### Level 2
#### Task 1: Predictive Modeling (Regression)
- Description: Build and evaluate a regression model to
- predict a continuous variable (e.g., house prices).


# Objectives:

- Split the dataset into training and testing sets.
- Train a linear regression model using scikit-learn.
- Evaluate the model using performance metrics like
- mean squared error (MSE) and R-squared.
- Experiment with multiple models (e.g., Decision Trees,
- Random Forest) and compare performance.
- Tools: Python, scikit-learn, pandas, matplotlib.

#### Import required libraries

In [3]:
# data manipulation libraries
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning libraries
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_squared_error, r2_score

#### Data loading

In [4]:
# Data Loading
data = pd.read_csv('house_data.csv')

In [5]:
# view the five rows of the data
data.head()

,price,bedRooms,bathRooms,lotSize,floors,basement,yearBuilt,yearRenovated,city,country
0,376000.0,-0.407038,-0.143346,-0.361260,2.815716,-0.670397,1.255990,-0.827295,0.774499,0.0
1,800000.0,0.722824,1.567825,3.997450,0.940960,-0.670397,1.222190,-0.827295,-1.554932,0.0
2,324000.0,-0.407038,0.198888,-0.374498,0.940960,-0.203111,1.222190,-0.827295,0.774499,0.0
3,549900.0,1.852686,0.883357,-0.205964,-0.933795,2.740788,0.275797,-0.827295,0.774499,0.0
4,320000.0,-0.407038,0.541123,-0.207233,0.940960,-0.670397,1.086991,-0.827295,-0.433354,0.0

In [6]:
# Drop the country column
data = data.drop(columns=['country'])

In [7]:
# view the data again 
data.head()

,price,bedRooms,bathRooms,lotSize,floors,basement,yearBuilt,yearRenovated,city
0,376000.0,-0.407038,-0.143346,-0.361260,2.815716,-0.670397,1.255990,-0.827295,0.774499
1,800000.0,0.722824,1.567825,3.997450,0.940960,-0.670397,1.222190,-0.827295,-1.554932
2,324000.0,-0.407038,0.198888,-0.374498,0.940960,-0.203111,1.222190,-0.827295,0.774499
3,549900.0,1.852686,0.883357,-0.205964,-0.933795,2.740788,0.275797,-0.827295,0.774499
4,320000.0,-0.407038,0.541123,-0.207233,0.940960,-0.670397,1.086991,-0.827295,-0.433354

#### split data into X and y

In [10]:
# drop the Target variable and assign it in y 
X = data.drop(columns=['price'])

# getting the target variable
y = data['price']

In [17]:
shape_of_X = X
shape_of_y = y
print('This is the shape of the X:', shape_of_X.head(), '\n')
print(f'This is the shape of y\n', shape_of_y)

This is the shape of the X:    bedRooms  bathRooms   lotSize    floors  basement  yearBuilt  \
0 -0.407038  -0.143346 -0.361260  2.815716 -0.670397   1.255990
1  0.722824   1.567825  3.997450  0.940960 -0.670397   1.222190
2 -0.407038   0.198888 -0.374498  0.940960 -0.203111   1.222190
3  1.852686   0.883357 -0.205964 -0.933795  2.740788   0.275797
4 -0.407038   0.541123 -0.207233  0.940960 -0.670397   1.086991

   yearRenovated      city
0      -0.827295  0.774499
1      -0.827295 -1.554932
2      -0.827295  0.774499
3      -0.827295  0.774499
4      -0.827295 -0.433354

This is the shape of y
 0       376000.000000
1       800000.000000
2       324000.000000
3       549900.000000
4       320000.000000
            ...
3920    308166.666667
3921    534333.333333
3922    416904.166667
3923    203400.000000
3924    220600.000000
Name: price, Length: 3925, dtype: float64

In [18]:
# assign the two variable back into X and y
shape_of_X = X
shape_of_y = y

#### Split the into train and test

In [21]:
# splitting the data into train and test
X_train, X_test,  y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
# initialize the LinearRegression 
lr = LinearRegression()
lr.fit(X_train, y_train) # Training the model

# initialize the RandomForest
rf = RandomForestRegressor(n_estimators=100, random_state=0) # train the model
rf.fit(X_train, y_train)

#initialize the DecisionTree
dt = DecisionTreeRegressor(random_state=0) # train the model
dt.fit(X_train, y_train)

# Make prediction
linear_pred = lr.predict(X_test)
random_pred = rf.predict(X_test)
decision_pred = dt.predict(X_test)

evaluation1 = mean_squared_error( y_test, linear_pred)
evaluation2 = mean_squared_error( y_test, random_pred)
evaluation3 = mean_squared_error( y_test, decision_pred)

print(f'The evaluation outcome of linear regresion', {evaluation1}, '\n')
print(f'The evaluation outcome random forest', {evaluation2}, '\n')
print(f'The evaluation outcome of decision tree', {evaluation3}, '\n')

print('------------------------------------------------------------------------------')

# R2 score
score1 = r2_score(y_test, linear_pred)
score2 = r2_score(y_test, random_pred)
score3 = r2_score(y_test, decision_pred)

print(f'The evaluation outcome of linear regresion using R2 score', {score1}, '\n')
print(f'The evaluation outcome random forest  using R2 score', {score2}, '\n')
print(f'The evaluation outcome of decision tree using R2 score', {score3})

The evaluation outcome of linear regresion {37202075894.9736}

The evaluation outcome random forest {25441876448.816666}

The evaluation outcome of decision tree {48141485871.89451}

------------------------------------------------------------------------------
The evaluation outcome of linear regresion using R2 score {0.24845862699234822}

The evaluation outcome random forest  using R2 score {0.4860334457621458}

The evaluation outcome of decision tree using R2 score {0.027465066924385884}